### ISSUE TITLE
Blocking Orders from being placed

### ISSUE THREAD

**Issue by InternetMedicineMan** [magepal/magento2-gmailsmtpapp#53]
So I've installed this and it seems to work really well. I've been testing it and emails work fine. Forgotten password sends off an email. Changing a password email goes out.

But then I try to place an order. If you place an order from the frontend it just says that the order failed. And I had no idea what was causing it. But then finally I placed an order from the admin and it came with a more specific error "Invalid MAIL FROM address provided". So I realized it was this module. Disable this module and I can place orders on the frontend and admin.

I don't understand why it's getting this error though. I've verified the domain and several emails in Amazon. Not to mention emails are sending just fine. Everything except order emails. This will not send an order email at all, and prevents any orders from even being placed.

I've played with what little settings there are such as Set Reply to, Set Return Path, Set From. And none of the settings change anything whether it's Yes or No.

Is there some log I could be checking? I don't even know what email it's trying, and why is it different than every other email that goes out? Maybe I can change the Order email some how? Although all the Magento from emails are set identical and it's verified in Amazon. Seems to be something strange going on, any help would be appreciated.

**Comment by srenon** [comment]
@InternetMedicineMan ... If all other sections are working, the only thing I can think of is that the sales email "from sender" is not authorized.

I will add better debugging shortly

**Comment by InternetMedicineMan** [comment]
The sales email as well as all from addresses are set to the exact same address. When it's running an order it seems to be using a completely different address, and that's what I'm having trouble figuring out. Would love to figure out what it is, where this address is coming from, it's just very strange. 

I can even take an existing order (created with this extension disabled) and make a comment on that order and notify the customer and it will process just fine. The email is delivered and it came from the from the sales email.

So it really confuses me why just order placement is being affected. And where this new from address is coming from.

**Comment by srenon** [comment]
@InternetMedicineMan ... I do know that other sites are using this with Amazon so the issue may be local to your store config. 

This going to be very hard for me to debug, but should be very simple for someone who have access to the server.

Are you using multi store?

Does the email belongs to the customer, is it random, does it change or is it constant when placing different orders?

**Comment by InternetMedicineMan** [comment]
I am using multi-store, it's just tentatively turned on for now as we plan on extending another store in the future, but nothing is active as a second store. All emails are set to the same address. There are no changes. All store configs use the same address, because it's the same company the two stores are just planned as "wholesale" and "consumer" as we have different ways we want to display the products.

As I mentioned interacting with an order emails a customer just fine, but creating an order does not. So is there any log anywhere that would log what is happening when it communicates with Amazon? The only thing reported is the error, but not what values are being used, that would be very helpful in discovering the root of the issue. I realize that I maybe forgetting a setting somewhere as I'm new to Magento.

**Comment by srenon** [comment]
@InternetMedicineMan ... Currently, there is no error log for that. Normally it would either work or not work, So you could easily test in the admin to see what the issue is.  But I'll build something in the near future. 

However, you could just modify these lines to debug and see what going on https://github.com/magepal/magento2-gmailsmtpapp/blob/master/Model/Transport.php#L88

I.e

```
        try {
            print_r($this->_message);
            parent::send($this->_message);
        } catch (\Exception $e) {
            throw new \Magento\Framework\Exception\MailException(new \Magento\Framework\Phrase($e->getMessage()), $e);
        }

```

Check to see what the value is for https://github.com/magepal/magento2-gmailsmtpapp/blob/master/Model/Transport.php#L54 

>message->setFrom($returnPathEmail);

Take a look at https://github.com/magento/magento2/issues/6954 ... Then review the raw header for an email that was sent correctly to see what address it is using

**Comment by InternetMedicineMan** [comment]
Okay I tried adding your lines to debug, from the admin no change, just the same single error was returned. From the frontend it just caused a perpetual load on submission, but if I remove it then it works again just returns the vague error message.

I looked at your other ticket, but I don't think that's the same issue, as I mentioned we have two stores, but it's all for the same company, all for the same email address. We have a single email "hello@domain" That's set for the default, it's set for Store 1, it's set for Store 2. It's set for Sales, it's set for customer service, it's set for everything, just one single email that is everywhere.

You mentioned checking to see what the value is for the SetFrom. But honestly I have no idea on how to do that. That's what I keep asking about, because I don't know how to check it, for some reason that value is wrong only when sending order emails. Anything else that tries to send out, goes out just fine and I get the email from hello@domain. I wish I could find what value it's trying to use because then I can track down where that's coming from and potentially solve the issue.

**Comment by srenon** [comment]
@InternetMedicineMan ... Since the frontend is all ajax request, it may be easier to test from the admin

Change https://github.com/magepal/magento2-gmailsmtpapp/blob/master/Model/Transport.php#L54
```
if ($returnPathEmail !== null && $dataHelper->getConfigSetFrom()) {
            $message->clearFrom();
            $message->setFrom($returnPathEmail);
            var_dump($returnPathEmail);
            die($returnPathEmail);
}
```
Then place and order.... you should get a white screen with the email

**Comment by InternetMedicineMan** [comment]
Not exactly sure what I'm doing to take a look at this variable. But I decided to swap out the "error" message on exception to be this variable, I assumed if the error is displaying on the admin maybe I could at least see what the variable contained. So I changed the code at Line 90 to the following:
`        try {
            parent::send($this->_message);
        } catch (\Exception $e) {
            throw new \Magento\Framework\Exception\MailException(new \Magento\Framework\Phrase($e->getMessage()), $returnPathEmail);
        }
    }
`

I'm not sure if this is giving me the desired result, but now when I place and order in the admin it comes back with this error message:

Order saving error: Notice: Undefined variable: returnPathEmail in /var/www/html/vendor/magepal/magento2-gmailsmtpapp/Model/Transport.php on line 90

Undefined Variable? Does this mean that the variable is empty when trying to save an order? I see where it is set up on line 32, and the default is null, but it shouldn't ever be null if it's set to yes or no? 

Just for fun I just manually set the $returnPathEmail to the single email value we use throughout the entire store. Now I just get a new error:

Could not read from email-smtp.us-east-1.amazonaws.com

I have no clue what's going on. It's like when processing an order all new rules are applied and I don't know where the issue is. 

I also just tried to switch the whole thing to run off of our Google Apps account, and just login through the account that is the single email we keep using. Figured that would solve everything. Nope, evidently this doesn't work on Google Apps? I keep getting invalid username and password, even though I just logged into the account. I assume it just is designed for Gmail not really Google Apps.

**Comment by InternetMedicineMan** [comment]
Well even just leaving it at Amazon and running a test email now comes back with 

Could not read from email-smtp.us-east-1.amazonaws.com

I might be blocked now or something. Further research needed. This means manually setting the return path may have worked.

**Comment by srenon** [comment]
You are getting "Undefined variable: returnPathEmail " because it is defined in a different method.

It does work with gmail or google app account.

What version of 2.x are you running?

**Comment by InternetMedicineMan** [comment]
The admin is ajax also, so it won't return a value for me on the var_dump() However when I try to add a comment to an order (which always sends properly) I get this in the comments section:

string(20) "hello@wondercide.com" hello@wondercide.com

So not sure why it would be defined in a different method, dumping it just shows a string. Or maybe you mean that the error needs to be defined in a different method to output properly? I guess that makes more sense. Of course this tells me nothing still, because the comments on the order always have worked, with the correct email, it's just placing an order that comes back with something funky. 

We are running the latest version 2.1.5 of course the last version didn't do anything but update the copyright, and I originally tried to get it to work with Google Apps on 2.1.3 and it wouldn't work so I just assumed it was designed for Gmail.

**Comment by srenon** [comment]
1. Log into the admin

2. Enter your email and password (do NOT save)

3. Go to the "test setting" and press the button

The let me know the result

**Comment by InternetMedicineMan** [comment]
With Amazon right now it just comes back "Too many connections try again later" so not sure with Amazon.

With Google Apps, I've always ever gotten:

5.7.8 Username and Password not accepted. Learn more at 5.7.8 https://support.google.com/mail/?p=BadCredentials j2sm1152389itj.30 - gsmtp

No matter what I've tried I get this error.

**Comment by srenon** [comment]
Do you follow this instruction https://support.google.com/accounts/answer/6010255 ?

**Comment by InternetMedicineMan** [comment]
Okay, that's what I was missing. I must have glossed over that and forgotten that little tidbit. Well now I can make it work with Google Apps. I actually kind of preferred Amazon, but Google Apps can fit the bill.

I completed and order and it works fine. I have it logging into a different account than "hello@" because I know that Google Apps generally reports the from address as "sales@ on behalf of hello@" if you choose a different from address. And the from address is just "sales@" instead, and the reply to is "hello@" so it's almost as if the from address really isn't being set for some reason. Not a big deal with Google Apps because it just chooses the login from address? Anyway not sure if that's helpful, but thought I would share.

**Comment by srenon** [comment]
@InternetMedicineMan .... this should be fixed in the latest code in master

**Comment by imsaiid** [comment]
The issue is still not fixed. Facing the same issue with Magento 2.2.3 and using the latest version of this extension. Any help?
